create TABLE `USERS` (
	`ID`	int	NOT NULL,
	`email`	varchar(50)	NOT NULL,
	`password`	varchar(255)	NULL,
	`nickname`	varchar(100)	NULL,
	`gender`	enum('Male', 'Female')	NULL,
	`address`	varchar(100)	NULL,
	`detailed_address`	varchar(255)	NULL
);

CREATE TABLE `LOCATION` (
	`ID`	INT	NOT NULL,
	`LOCATION_NAME`	VARCHAR(200)	NULL,
	`COVER_IMG_URL`	VARCHAR(1000)	NULL,
	`COST`	INT	NULL,
	`LIKE_CNT`	INT	NULL,
	`GRADE`	DOUBLE	NULL,
	`GRADE_CNT`	INT	NULL,
	`OPEN_INFO`	VARCHAR(200)	NULL,
	`CERTIFICATEION`	VARCHAR(200)	NULL,
	`X`	DOUBLE	NULL,
	`Y`	DOUBLE	NULL
);

CREATE TABLE `POST` (
	`POST_ID`	INT	NOT NULL,
	`WRITER_PROFILE_IMG`	VARCHAR(1000)	NULL,
	`WRITER_NICKNAME`	VARCHAR(100)	NULL,
	`WRITER_LOCATION`	VARCHAR(255)	NULL,
	`WRITER_RANK_IMG`	VARCHAR(1000)	NULL,
	`POST_TITLE`	VARCHAR(100)	NULL,
	`POST_CONTENT`	VARCHAR(500)	NULL,
	`LIKE_CNT`	INT	NULL	DEFAULT 0,
	`REG_DATE`	DATETIME	NULL,
	`MOD_DATE`	DATETIME	NULL
);

CREATE TABLE `IMAGES` (
	`IMAGES_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL
);

CREATE TABLE `CRI` (
	`ID`	INT	NULL,
	`X`	DOUBLE	NULL,
	`Y`	DOUBLE	NULL,
	`DO`	VARCHAR(50)	NULL,
	`GU`	VARCHAR(50)	NULL,
	`SI`	VARCHAR(50)	NULL,
	`LOCATION_NAME`	VARCHAR(500)	NULL
);

CREATE TABLE `LOCATION_REVIEW` (
	`ID`	INT	NOT NULL,
	`LOCATION_ID`	INT	NULL,
	`COMMENT`	TEXT	NULL,
	`GRADE`	DOUBLE	NOT NULL,
	`DATE`	DATETIME	NULL,
	`WRITER_ID`	INT	NULL
);

CREATE TABLE `LOCATION_TAG` (
	`ID`	INT	NOT NULL,
	`TAG_NAME`	VARCHAR(50)	NULL,
	`LOCATION_ID`	INT	NULL
);

CREATE TABLE `LOCATION_OPTION` (
	`ID`	INT	NOT NULL,
	`LOCATION_ID`	INT	NULL,
	`OPTION_IMG_URL`	VARCHAR(1000)	NULL,
	`OPTION_COST`	INT	NULL,
	`OPTION_NAME`	VARCHAR(50)	NULL
);

CREATE TABLE `UserProfile` (
	`USER_ID`	INT	NOT NULL,
	`PROFILE_IMAGE`	VARCHAR(1000)	NULL,
	`GRADE`	INT	NULL,
	`GRADE_IMAGE`	VARCHAR(1000)	NULL,
	`STATUS_MESSAGE`	VARCHAR(255)	NULL
);

CREATE TABLE `LIKES` (
	`LIKE_ID`	INT	NOT NULL,
	`USER_ID`	INT	NULL,
	`POST_ID`	INT	NULL,
	`TRAVEL_ID`	INT	NULL
);

CREATE TABLE `LOCATION_IMG` (
	`ID`	INT	NOT NULL,
	`IMAGE_URL`	VARCHAR(1000)	NULL,
	`LOCATION_ID`	INT	NULL
);

CREATE TABLE `RESERVATIONS` (
	`RESERVATION_ID`	INT	NOT NULL,
	`USER_ID`	INT	NULL,
	`RESERVATION_NUM`	VARCHAR(100)	NULL,
	`RESERVATION_DATE`	DATETIME	NULL,
	`RESERVATION_PLACE`	VARCHAR(50)	NULL,
	`PAYMENT_STATUS`	VARCHAR(50)	NULL
);

CREATE TABLE `LOCATION_REVIEW_IMG` (
	`ID`	INT	NOT NULL,
	`REVIEW_ID`	INT	NULL,
	`IMAGE_URL`	VARCHAR(1000)	NULL
);

CREATE TABLE `BOARD_COMMENT` (
	`COMMENT_ID`	INT	NOT NULL,
	`POST_ID`	INT	NULL,
	`COMMENTER_ID`	VARCHAR(255)	NULL,
	`COMMENTER_PROFILE_IMG`	VARCHAR(1000)	NULL,
	`COMMENTER_NICKNAME`	VARCHAR(100)	NULL,
	`COMMENTER_RANK`	VARCHAR(1000)	NULL,
	`COMMENT_CONTENT`	VARCHAR(500)	NULL,
	`LIKE_CNT`	INT	NULL,
	`REG_DATE`	DATETIME	NULL,
	`MOD_DATE`	DATETIME	NULL
);

CREATE TABLE `BOARD_REPLY` (
	`REPLY_ID`	INT	NOT NULL,
	`COMMENT_ID`	INT	NULL,
	`REPLIER_ID`	VARCHAR(255)	NULL,
	`REPLIER_PROFILE_IMG`	VARCHAR(1000)	NULL,
	`REPLIER_NICKNAME`	VARCHAR(100)	NULL,
	`REPLIER_RANK`	VARCHAR(1000)	NULL,
	`REPLY_CONTENT`	varchar(500)	NULL,
	`LIKE_CNT`	INT	NULL,
	`REG_DATE`	DATETIME	NULL,
	`MOD_DATE`	DATETIME	NULL
);

CREATE TABLE `LOCATION_LIKE` (
	`ID`	INT	NOT NULL,
	`LOCATION_ID`	INT	NULL,
	`WRITER_ID`	INT	NULL
);

CREATE TABLE `BOARD_LIKE` (
	`LIKE_ID`	INT	NOT NULL,
	`USER_ID`	VARCHAR(255)	NULL,
	`POST_ID`	INT	NULL
);

CREATE TABLE `BOARD_REPLY_LIKE` (
	`LIKE_ID`	INT	NOT NULL,
	`USER_ID`	VARCHAR(255)	NULL,
	`REPLY_ID`	INT	NULL
);

CREATE TABLE `BOARD_COMMENT_LIKE` (
	`LIKE_ID`	INT	NOT NULL,
	`USER_ID`	VARCHAR(255)	NULL,
	`COMMENT_ID`	INT	NULL
);


ALTER TABLE `USERS` ADD CONSTRAINT `PK_USERS` PRIMARY KEY (
	`ID`
);

ALTER TABLE `LOCATION` ADD CONSTRAINT `PK_LOCATION` PRIMARY KEY (
	`ID`
);

ALTER TABLE `POST` ADD CONSTRAINT `PK_POST` PRIMARY KEY (
	`POST_ID`
);

ALTER TABLE `IMAGES` ADD CONSTRAINT `PK_IMAGES` PRIMARY KEY (
	`IMAGES_ID`
);

ALTER TABLE `CRI` ADD CONSTRAINT `PK_CRI` PRIMARY KEY (
	`ID`
);

ALTER TABLE `LOCATION_REVIEW` ADD CONSTRAINT `PK_LOCATION_REVIEW` PRIMARY KEY (
	`ID`
);

ALTER TABLE `LOCATION_TAG` ADD CONSTRAINT `PK_LOCATION_TAG` PRIMARY KEY (
	`ID`
);

ALTER TABLE `LOCATION_OPTION` ADD CONSTRAINT `PK_LOCATION_OPTION` PRIMARY KEY (
	`ID`
);

ALTER TABLE `UserProfile` ADD CONSTRAINT `PK_USERPROFILE` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `LIKES` ADD CONSTRAINT `PK_LIKES` PRIMARY KEY (
	`LIKE_ID`
);

ALTER TABLE `LOCATION_IMG` ADD CONSTRAINT `PK_LOCATION_IMG` PRIMARY KEY (
	`ID`
);

ALTER TABLE `RESERVATIONS` ADD CONSTRAINT `PK_RESERVATIONS` PRIMARY KEY (
	`RESERVATION_ID`
);

ALTER TABLE `LOCATION_REVIEW_IMG` ADD CONSTRAINT `PK_LOCATION_REVIEW_IMG` PRIMARY KEY (
	`ID`
);

ALTER TABLE `BOARD_COMMENT` ADD CONSTRAINT `PK_BOARD_COMMENT` PRIMARY KEY (
	`COMMENT_ID`
);

ALTER TABLE `BOARD_REPLY` ADD CONSTRAINT `PK_BOARD_REPLY` PRIMARY KEY (
	`REPLY_ID`
);

ALTER TABLE `LOCATION_LIKE` ADD CONSTRAINT `PK_LOCATION_LIKE` PRIMARY KEY (
	`ID`
);

ALTER TABLE `BOARD_LIKE` ADD CONSTRAINT `PK_BOARD_LIKE` PRIMARY KEY (
	`LIKE_ID`
);

ALTER TABLE `BOARD_REPLY_LIKE` ADD CONSTRAINT `PK_BOARD_REPLY_LIKE` PRIMARY KEY (
	`LIKE_ID`
);

ALTER TABLE `BOARD_COMMENT_LIKE` ADD CONSTRAINT `PK_BOARD_COMMENT_LIKE` PRIMARY KEY (
	`LIKE_ID`
);


ALTER TABLE `rank` ADD CONSTRAINT `PK_RANK` PRIMARY KEY (
	`rank_id`,
	`id`
);

ALTER TABLE `post` ADD CONSTRAINT `PK_POST` PRIMARY KEY (
	`post_id`
);

ALTER TABLE `comment` ADD CONSTRAINT `PK_COMMENT` PRIMARY KEY (
	`comment_id`
);

ALTER TABLE `rank` ADD CONSTRAINT `FK_user_TO_rank_1` FOREIGN KEY (
	`id`
)
REFERENCES `user` (
	`id`
);

ALTER TABLE `user` ADD CONSTRAINT `PK_USER` PRIMARY KEY (  `id` )
