/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2024-08-05 08:37:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.location;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <title>반응형 레이아웃</title>\r\n");
      out.write("    <!-- js link -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.3/jquery-ui.min.js></script>\r\n");
      out.write("    <!--kakao Link-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=9ba1ee8768e59dc81c31a27c0e72ea4a&libraries=services\"></script>\r\n");
      out.write("    <!-- bootstrap5 link -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- style css link -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/location.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/sidebar.jsp", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\r\n");
      out.write("    <!-- ⚠️⚠️⚠️ 이 밑 부분 (content 부분)만 수정하세요. ⚠️⚠️⚠️ -->\r\n");
      out.write("    <!-- ⚠️⚠️⚠️ 이 밑 부분 (content 부분)만 수정하세요. ⚠️⚠️⚠️ -->\r\n");
      out.write("    <!-- 👇👇👇 이 밑 부분 (content 부분)만 수정하세요. 👇👇👇 -->\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div id=\"main\">\r\n");
      out.write("            <input type=\"hidden\" id=\"contextPath\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            <!--filter-->\r\n");
      out.write("            <div id=\"filter-form\" style=\"display: none;\">\r\n");
      out.write("                <div class=\"d-flex\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/filter.svg\" alt=\"\" id=\"filter-back-button\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--area-filer-->\r\n");
      out.write("                <div id=\"area-filer\">\r\n");
      out.write("                    <p style=\"display: block; width: 5vw; height: 3vh; font-weight: bold;\">지역</p>\r\n");
      out.write("                    <div id=\"areas\" class=\"d-flex\">\r\n");
      out.write("                        <p class=\"area\">서율</p>\r\n");
      out.write("                        <p class=\"area\">인천</p>\r\n");
      out.write("                        <p class=\"area\">경기</p>\r\n");
      out.write("                        <p class=\"area\">강원</p>\r\n");
      out.write("                        <p class=\"area\">대전</p>\r\n");
      out.write("                        <p class=\"area\">세종</p>\r\n");
      out.write("                        <p class=\"area\">충청</p>\r\n");
      out.write("                        <p class=\"area\">대구</p>\r\n");
      out.write("                        <p class=\"area\">경상</p>\r\n");
      out.write("                        <p class=\"area\">울산</p>\r\n");
      out.write("                        <p class=\"area\">부산</p>\r\n");
      out.write("                        <p class=\"area\">광주</p>\r\n");
      out.write("                        <p class=\"area\">전라</p>\r\n");
      out.write("                        <p class=\"area\">제주</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--price-filer-->\r\n");
      out.write("                <div id=\"price-filer\"  class=\"d-flex\">\r\n");
      out.write("                    <p style=\"display: block; width: 5vw; height: 3vh; font-weight: bold;\">가격</p>\r\n");
      out.write("                    <p id=\"price-min\" value ='100000'>100,000</p>\r\n");
      out.write("                    <div class=\"price-progress\" id=\"price-progress\">\r\n");
      out.write("                        <div id=\"draggable-point-1\" style=\"left:75%;position:absolute;\" class=\"draggable ui-widget-content price-point\">\r\n");
      out.write("                            <div class=\"price-progress-handle\"></div>\r\n");
      out.write("                            <div class=\"price-handle-value\" id=\"price-handle-max\">750,000</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"draggable-point-2\" style=\"left:55%;position:absolute;\" class=\"draggable ui-widget-content price-point\">\r\n");
      out.write("                            <div class=\"price-progress-handle\"></div>\r\n");
      out.write("                            <div class=\"price-handle-value\" id=\"price-handle-min\">550,000</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"price-progress-bar\" class=\"bar\" style=\"width:20%; left:55%; position:absolute\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p id=\"price-max\" value ='1000000'>1,000,000+</p>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!--serchBar-->\r\n");
      out.write("            <div id=\"serchArea\">\r\n");
      out.write("                <!--serch-->\r\n");
      out.write("                <div id=\"serch-form\" >\r\n");
      out.write("                    <input type=\"text\" id=\"serchBar\" placeholder=\"검색\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/filter.svg\" alt=\"\" id=\"filter-button\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--only line-->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!--kakao Map-->\r\n");
      out.write("            <div id=\"kakaoMap\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--result-->\r\n");
      out.write("            <div id =\"serchResultList\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--modal-->\r\n");
      out.write("            <div class=\"modal fade\" id=\"resultModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"resultModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                <div class=\"modal-dialog modal-dialog-left\" style=\"max-width: 80vw;\" role=\"document\" >\r\n");
      out.write("                    <div class=\"modal-content\">\r\n");
      out.write("                        <div class=\"modal-header border-0 justify-content-end\">\r\n");
      out.write("                            <div id=\"link_planArea\" class=\"d-flex\">\r\n");
      out.write("                              <p>여행계획에 추가</p>\r\n");
      out.write("                              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/plan_link_logo.svg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/pick_location.svg\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/share_location.svg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--modal body 1-2-1 1-1-2-->\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div class=\"row\" style=\"height: 40vh;\">\r\n");
      out.write("                                    <div class=\"col-3 border result-container\" >\r\n");
      out.write("                                        <div class=\"col-3 border\" id=\"resultModalImg\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/Food.svg);\">\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-6 border result-container\">\r\n");
      out.write("                                        <div id=\"resultModalMap\">\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-3 border result-container\" >\r\n");
      out.write("                                        <div id=\"resultModalComment\">\r\n");
      out.write("                                            <p>후기</p>\r\n");
      out.write("                                            <div class=\"commentArea\">\r\n");
      out.write("                                                <div class=\"d-flex\">\r\n");
      out.write("                                                    <div class=\"grade\">\r\n");
      out.write("                                                        ⭐⭐⭐⭐⭐\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <p class=\"place_name\">TEST</p>\r\n");
      out.write("                                                    <p class=\"option_name\">TEST</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"comment\">\r\n");
      out.write("                                                    <p>\r\n");
      out.write("                                                        AAAAAAAA<br>AAAAAAAAA\r\n");
      out.write("                                                    </p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"commentArea\">\r\n");
      out.write("                                                <div class=\"d-flex\">\r\n");
      out.write("                                                    <div class=\"grade\">\r\n");
      out.write("                                                        ⭐⭐⭐⭐⭐\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <p class=\"place_name\">TEST</p>\r\n");
      out.write("                                                    <p class=\"option_name\">TEST</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"comment\">\r\n");
      out.write("                                                    <p>\r\n");
      out.write("                                                        AAAAAAAA<br>AAAAAAAAA\r\n");
      out.write("                                                    </p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"commentArea\">\r\n");
      out.write("                                                <div class=\"d-flex\">\r\n");
      out.write("                                                    <div class=\"grade\">\r\n");
      out.write("                                                        ⭐⭐⭐⭐⭐\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <p class=\"place_name\">TEST</p>\r\n");
      out.write("                                                    <p class=\"option_name\">TEST</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"comment\">\r\n");
      out.write("                                                    <p>\r\n");
      out.write("                                                        AAAAAAAA<br>AAAAAAAAA\r\n");
      out.write("                                                    </p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"row\" style=\"height: 40vh;\">\r\n");
      out.write("                                    <div class=\"col-3 border\" id=\"resultModalDatas\">\r\n");
      out.write("                                        <div class=\"d-flex\">\r\n");
      out.write("                                            <p id=\"place_name\">TEST</p>\r\n");
      out.write("                                            <div id=\"grade\">\r\n");
      out.write("                                                ⭐⭐⭐⭐⭐\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"d-flex serch-certification\">\r\n");
      out.write("                                            <img src=\"\" alt=\"\" class=\"certification-img\">\r\n");
      out.write("                                            <p class=\"certification-title\"></p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"price-info\">\r\n");
      out.write("                                            <p>금액</p>\r\n");
      out.write("                                            <p class=\"price\">금액</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"direction-info\">\r\n");
      out.write("                                            <p>찾아가시는 길</p>\r\n");
      out.write("                                            <p class=\"direction\">TEST DIRECTIOON</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"location-info\">\r\n");
      out.write("                                            <p>위치</p>\r\n");
      out.write("                                            <p class=\"location\">TEST WHERE</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-3 border\" id=\"resultModalBooking\">\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"d-flex\" id=\"book-men\">\r\n");
      out.write("                                            <div style=\"padding: 6px;\">예약인원</div>\r\n");
      out.write("\r\n");
      out.write("                                            <button class=\"btn dropdown-toggle\" type=\"button\" id=\"bookMen-dropDown\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" data-bs-auto-close=\"outside\">\r\n");
      out.write("                                                예약인원수\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                            <div class=\"dropdown-menu\" >\r\n");
      out.write("                                                <form>\r\n");
      out.write("                                                    <div class=\"form-group\">\r\n");
      out.write("                                                        <label for=\"book-adult\">성인</label>\r\n");
      out.write("                                                        <input type=\"text\" class=\"form-control\" id=\"book-adult\" placeholder=\"0명\">\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"form-group\">\r\n");
      out.write("                                                        <label for=\"book-child\">아동</label>\r\n");
      out.write("                                                        <input type=\"text\" class=\"form-control\" id=\"book-child\" placeholder=\"0명\">\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </form>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"d-flex\" id=\"book-option\">\r\n");
      out.write("                                            <div style=\"padding: 6px;\">객실종류</div>\r\n");
      out.write("                                            <button class=\"btn dropdown-toggle\" id=\"book-option-button\" type=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                                                option1\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                                <li><button class=\"dropdown-item book-opiton-item\" type=\"button\">option1</button></li>\r\n");
      out.write("                                                <li><button class=\"dropdown-item book-opiton-item\" type=\"button\">option2</button></li>\r\n");
      out.write("                                                <li><button class=\"dropdown-item book-opiton-item\" type=\"button\">option3</button></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <!--carecell-->\r\n");
      out.write("                                        <div id=\"optionImage-carouse\" class=\"carousel slide\">\r\n");
      out.write("                                            <div class=\"carousel-inner\">\r\n");
      out.write("                                                <div class=\"carousel-item active\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/Activity.svg\" class=\"d-block w-100  \" alt=\"...\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"carousel-item\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/Activity.svg\" class=\"d-block w-100 \" alt=\"...\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"carousel-item\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/Activity.svg\" class=\"d-block w-100 \" alt=\"...\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#optionImage-carouse\" data-bs-slide=\"prev\">\r\n");
      out.write("                                                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                                <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                            <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#optionImage-carouse\" data-bs-slide=\"next\">\r\n");
      out.write("                                                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                                <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <button class=\"\" id=\"book-button\">예약</button>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-6 border\" id=\"resultModalCalender\">\r\n");
      out.write("                                        <div class=\"container mt-4\">\r\n");
      out.write("\r\n");
      out.write("                                            <div id=\"calendar-wrapper\" class=\"border rounded p-3 d-flex\" style='background-color: #FFF' >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                <!--번트1--->\r\n");
      out.write("                                                <button id=\"prev\" class=\"btn calendar-button\">&lt;</button>\r\n");
      out.write("                                                <!-- 달력1-->\r\n");
      out.write("                                                <div class=\"calendar\">\r\n");
      out.write("                                                    <h2 class=\"month-year\" id=\"cur-month\">TEST</h2>\r\n");
      out.write("                                                    <div class=\"calendar-days\" >\r\n");
      out.write("                                                        <div class=\"day-name\">일</div>\r\n");
      out.write("                                                        <div class=\"day-name\">월</div>\r\n");
      out.write("                                                        <div class=\"day-name\">화</div>\r\n");
      out.write("                                                        <div class=\"day-name\">수</div>\r\n");
      out.write("                                                        <div class=\"day-name\">목</div>\r\n");
      out.write("                                                        <div class=\"day-name\">금</div>\r\n");
      out.write("                                                        <div class=\"day-name\">토</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"calendar-body\" id=\"cur-calender\">\r\n");
      out.write("                                                        <!-- Calendar dates will be inserted here by JavaScript -->\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <!--달력2-->\r\n");
      out.write("                                                <div class=\"calendar\">\r\n");
      out.write("                                                    <h2 class=\"month-year\" id=\"next-month\">TEST</h2>\r\n");
      out.write("                                                    <div  class=\"calendar-days\" >\r\n");
      out.write("                                                        <div class=\"day-name\">일</div>\r\n");
      out.write("                                                        <div class=\"day-name\">월</div>\r\n");
      out.write("                                                        <div class=\"day-name\">화</div>\r\n");
      out.write("                                                        <div class=\"day-name\">수</div>\r\n");
      out.write("                                                        <div class=\"day-name\">목</div>\r\n");
      out.write("                                                        <div class=\"day-name\">금</div>\r\n");
      out.write("                                                        <div class=\"day-name\">토</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div  class=\"calendar-body\" id=\"next-calendar\">\r\n");
      out.write("                                                        <!-- Calendar dates will be inserted here by JavaScript -->\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <!--번트2--->\r\n");
      out.write("                                                <button id=\"next\" class=\"btn calendar-button\">&gt;</button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 👆👆👆 윗 부분 (content 부분)만 수정하세요. 👆👆👆 -->\r\n");
      out.write("    <!-- ⚠️⚠️⚠️ 윗 부분 (content 부분)만 수정하세요. ⚠️⚠️⚠️ -->\r\n");
      out.write("    <!-- ⚠️⚠️⚠️ 윗 부분 (content 부분)만 수정하세요. ⚠️⚠️⚠️ -->\r\n");
      out.write("</div>\r\n");
      out.write("<!--script-->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/location.js\"></script>\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
