/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2024-08-05 08:36:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <!-- css 초기화 -->\r\n");
      out.write("    <!-- servlet-context.xml에 /static/** 설정 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/reset.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/login-joining.css\">\r\n");
      out.write("    <script\r\n");
      out.write("            src=\"https://code.jquery.com/jquery-3.7.1.js\"\r\n");
      out.write("            integrity=\"sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=\"\r\n");
      out.write("            crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/login-joining.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--pageContext.request.contextPath: WebServer의 root path인 webapp 폴더(http://localhost:8090)-->\r\n");
      out.write("<!-- Login Page -->\r\n");
      out.write("<div id=\"login-page-container\">\r\n");
      out.write("    <!-- left content -->\r\n");
      out.write("    <div id=\"login-left-content\">\r\n");
      out.write("        <div id=\"login-page-img\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/LoginPageImg.jpg\" alt=\"left-img\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- right content -->\r\n");
      out.write("    <div id=\"login-right-content\">\r\n");
      out.write("\r\n");
      out.write("        <!-- login Page -->\r\n");
      out.write("        <div id=\"login\" class=\"login-content\">\r\n");
      out.write("            <a href=\"\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/TeamProjectLogo.png\" alt=\"logo\" class=\"main-logo\">\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <h1>comma</h1>\r\n");
      out.write("            <p>당신의 일상에 '쉼표'를 선물하세요.</p>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"login-container1\">\r\n");
      out.write("                <div id=\"focus-login-username\" class=\"input-group\">\r\n");
      out.write("                    ");
      out.write("<label for=\"username\">ID</label>\r\n");
      out.write("                    <input type=\"text\" id=\"login-username\" class=\"login-input\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"focus-login-password\" class=\"input-group\">\r\n");
      out.write("                    ");
      out.write("<label for=\"password\">PW</label>\r\n");
      out.write("                    <input type=\"password\" id=\"login-password\" class=\"login-input\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"btn-group\">\r\n");
      out.write("                    <button id=\"loginBtn\" class=\"btn\">LOGIN</button>\r\n");
      out.write("                    <button id=\"showSignup\" class=\"btn\">JOIN</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- join page -->\r\n");
      out.write("        <div id=\"join\" class=\"login-content hidden\">\r\n");
      out.write("            <a href=\"\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/TeamProjectLogo.png\" alt=\"logo\" class=\"main-logo\">\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <h1>comma</h1>\r\n");
      out.write("            <p>join the membership</p>\r\n");
      out.write("            <div id=\"login-container2\">\r\n");
      out.write("                <div id=\"focus-join-username\" class=\"input-group\">\r\n");
      out.write("                    <label for=\"join-username\">ID</label>\r\n");
      out.write("                    <input type=\"text\" id=\"join-username\" class=\"login-input\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"focus-join-password\" class=\"input-group\">\r\n");
      out.write("                    <label for=\"password\">PW</label>\r\n");
      out.write("                    <input type=\"password\" id=\"join-password\" class=\"login-input\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"focus-join-passwordChk\" class=\"input-group\">\r\n");
      out.write("                    <label for=\"password\">PW CHECK</label>\r\n");
      out.write("                    <input type=\"password\" id=\"passwordChk\" class=\"login-input\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"focus-join-nickname\" class=\"input-group\">\r\n");
      out.write("                    <label for=\"nickname\">NAME</label>\r\n");
      out.write("                    <input type=\"text\" id=\"nickname\" class=\"login-input\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"btn-group\">\r\n");
      out.write("                    <button id=\"male\" class=\"btn\" value=\"MALE\">MALE</button>\r\n");
      out.write("                    <button id=\"female\" class=\"btn\" value=\"FEMALE\">FEMALE</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"residence-group\">\r\n");
      out.write("                    <div id=\"residence\">\r\n");
      out.write("                        WEHRE YOU LIVE\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <select name=\"residence\" id=\"residence-list\">\r\n");
      out.write("                            <option value=\"서울\">서울</option>\r\n");
      out.write("                            <option value=\"경기\">경기</option>\r\n");
      out.write("                            <option value=\"인천\">인천</option>\r\n");
      out.write("                            <option value=\"강원\">강원</option>\r\n");
      out.write("                            <option value=\"대구\">대구</option>\r\n");
      out.write("                            <option value=\"대전\">대전</option>\r\n");
      out.write("                            <option value=\"광주\">광주</option>\r\n");
      out.write("                            <option value=\"울산\">울산</option>\r\n");
      out.write("                            <option value=\"충남\">충남</option>\r\n");
      out.write("                            <option value=\"충북\">충북</option>\r\n");
      out.write("                            <option value=\"경남\">경남</option>\r\n");
      out.write("                            <option value=\"경북\">경북</option>\r\n");
      out.write("                            <option value=\"전남\">전남</option>\r\n");
      out.write("                            <option value=\"전북\">전북</option>\r\n");
      out.write("                            <option value=\"제주\">제주</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                    <input type=\"text\" id=\"residence-input\" class=\"login-input\" placeholder=\"상세지역을 입력하세요.\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"btn-group\">\r\n");
      out.write("                    <button id=\"signupBtn\" class=\"btn\">JOIN</button>\r\n");
      out.write("                    <button id=\"showLogin\" class=\"btn\">CANCEL</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Modal -->\r\n");
      out.write("        <div id=\"myModal\" class=\"modal\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div id=\"modal-close-box\">\r\n");
      out.write("                    <span id=\"modal-close\">&times;</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"residenceDetails-box\">\r\n");
      out.write("                    <textarea id=\"residenceDetails\" class=\"large-textarea\" placeholder=\"상세 지역을 입력하세요...\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"saveBtn-box\">\r\n");
      out.write("                    <button id=\"saveBtn\" class=\"modal-btn\">Save</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(()=>{\r\n");
      out.write("        $('#loginBtn').on('click', () => {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: '/member/main.do',\r\n");
      out.write("                type: \"get\",\r\n");
      out.write("                contentType: \"x-www-form-urlencoded\",\r\n");
      out.write("                success: (page) => {\r\n");
      out.write("                    $(\"body\").html(page)\r\n");
      out.write("                },\r\n");
      out.write("                error: (err) => {\r\n");
      out.write("                    console.log(err);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        })\r\n");
      out.write("    })\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
